
jobs:

    - job:
      displayName: 'Build and Test Generation Tool'
      pool:
        vmImage: 'macOS-latest'
      strategy:
        matrix:
          Python38:
            python.version: '3.8'
          Python39:
            python.version: '3.9'
          Python310:
            python.version: '3.10'
        maxParallel: 4
    
      steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
          architecture: 'x64'
    
      - script: python3 -m venv $(System.DefaultWorkingDirectory)
        displayName: Create virtual environment
    
      - script: |
          source bin/activate
          curl -sSL https://install.python-poetry.org | python3 -
          $HOME/.local/bin/poetry install
        displayName: 'Install Poetry'
    
      - script: |
          source bin/activate
          python3 -m black -l 100 --check localizedstringkit/*.py tests/*.py
        displayName: 'Format Check (Black)'
    
      - script: |
          source bin/activate
          python3 -m pylint --rcfile=pylintrc localizedstringkit tests
        displayName: 'Lint'
    
      - script: |
          source bin/activate
          python3 -m mypy --ignore-missing-imports localizedstringkit/ tests/
        displayName: 'Type Check'
    
      - script: |
          source bin/activate
          python3 -m pytest tests --cov=localizedstringkit --cov-report xml --doctest-modules --junitxml=junit/test-results.xml
        displayName: 'pytest'
    
      - task: PublishTestResults@2
        inputs:
          testResultsFiles: '**/test-results.xml'
          testRunTitle: 'Python $(python.version)'
        condition: succeededOrFailed()
    
      # Publish Code Coverage Results
      - task: PublishCodeCoverageResults@1
        inputs:
          codeCoverageTool: 'cobertura'
          summaryFileLocation: $(System.DefaultWorkingDirectory)/coverage.xml
